<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.11.0
 * FormDin Version: 4.11.0
 * 
 */

if ( !function_exists( 'cargabd_cnpjrfb_autoload') ) {
    function cargabd_cnpjrfb_autoload( $class_name )
    {
        // Define paths to check
        $dirs = [
            __DIR__,                                // controllers (current)
            __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'helpers', // helpers
        ];

        foreach ($dirs as $dir) {
            $path = $dir . DIRECTORY_SEPARATOR . $class_name . '.class.php';
            if (file_exists($path)){
                require_once $path;
                return true;
            }
        }
        return false;
    }
    spl_autoload_register('cargabd_cnpjrfb_autoload');
}