version: '3.8'

services:
  app:
    build:
      dockerfile: adianti_debian12_php8.2.Dockerfile
      context: .
    image: cnpj-app:latest
    container_name: cnpj_app
    restart: unless-stopped
    ports:
      - "8081:80"
      - "9003:9003"
    environment:
      - TIMEZONE=America/Sao_Paulo
    volumes:
      - ./php.ini:/etc/php/8.2/apache2/php.ini:ro
      - ./php-custom.ini:/etc/php/8.2/cli/conf.d/99-custom.ini:ro
      - ./php-custom.ini:/etc/php/8.2/apache2/conf.d/99-custom.ini:ro
      - ./www:/var/www/html:rw
      - ./log_apache:/var/log/apache2:rw
      - ./extracted_files:/var/opt/dados_receita/extracted_files:rw # Shared volume for downloaded CSVs
    networks:
      - cnpj_net

  db:
    image: mariadb:10.11
    container_name: cnpj_db
    restart: unless-stopped
    command: --max_allowed_packet=512M --innodb_buffer_pool_size=1G --innodb_log_file_size=256M --innodb_flush_log_at_trx_commit=2
    environment:
      MYSQL_ROOT_PASSWORD: root_password_changeme
      MYSQL_DATABASE: cnpj_db
      MYSQL_USER: cnpj_user
      MYSQL_PASSWORD: cnpj_password
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb_logs:/var/log/mysql
      - ./extracted_files:/var/opt/dados_receita/extracted_files:ro # Read-only access to CSVs for LOAD DATA INFILE if needed
    networks:
      - cnpj_net
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: cnpj_adminer
    restart: always
    networks:
      - cnpj_net
    ports:
      - "8082:8080"

  phpmyadmin:
    image: phpmyadmin
    container_name: cnpj_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 100M
    ports:
      - "8083:80"
    networks:
      - cnpj_net

networks:
  cnpj_net:
    driver: bridge

volumes:
  mariadb_data:
