version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile.slim
      context: .
    image: cnpj-app:latest
    container_name: cnpj_app
    restart: unless-stopped
    ports:
      - "8081:80"
      - "9003:9003"
    environment:
      - TIMEZONE=America/Sao_Paulo
      - DB_HOST=mysql # Nome do serviço no stack Orion (ou nome_da_stack_mysql)
      - DB_PORT=3306
      - DB_NAME=cnpjrfb_2026
      - DB_USER=root
      - DB_PASSWORD=dab3cdfdde734471840f5179d1299d37
      - EXTRACTED_FILES_PATH=/var/www/html/cargabd/extracted
    volumes:
      - /root/cnpj/php.ini:/etc/php/8.2/apache2/php.ini:ro
      - /root/cnpj/php-custom.ini:/etc/php/8.2/cli/conf.d/99-custom.ini:ro
      - /root/cnpj/php-custom.ini:/etc/php/8.2/apache2/conf.d/99-custom.ini:ro
      - /root/cnpj/www:/var/www/html:rw
      - /root/cnpj/log_apache:/var/log/apache2:rw
      - extracted_files:/var/www/html/cargabd/extracted # Volume nomeado para persistência
    networks:
      - TaruZapNet
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.cnpj_app.rule=Host(`cnpjrfb.agenciataruga.com`)
        - traefik.http.routers.cnpj_app.entrypoints=websecure
        - traefik.http.routers.cnpj_app.tls.certresolver=letsencryptresolver
        - traefik.http.services.cnpj_app.loadbalancer.server.port=80
        - traefik.http.services.cnpj_app.loadbalancer.passHostHeader=true

networks:
  TaruZapNet:
    external: true
    name: TaruZapNet

volumes:
  extracted_files:
