CREATE TABLE IF NOT EXISTS monitoramento_rfb (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pasta_rfb VARCHAR(20) NOT NULL UNIQUE, -- Ex: '2026-01'
    status VARCHAR(20) NOT NULL DEFAULT 'NEW', -- NEW, PENDING_APPROVAL, PROCESSING, COMPLETED, ERROR
    data_detectada DATETIME DEFAULT CURRENT_TIMESTAMP,
    data_importacao DATETIME NULL,
    log TEXT,
    tentativas INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
