<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGenAd: https://github.com/bjverde/sysgenad
 * Download Formdin5 Framework: https://github.com/bjverde/formDin5
 * 
 * SysGen  Version: 0.6.0
 * FormDin Version: 5.0.0
 * 
 * System cnpjrfb created in: 2021-11-19 22:41:06
 */


//Veja como configurar conforme o Banco de Dados
//https://www.adianti.com.br/framework-quickstart
return [
     "host" => "my_mysql8"
    ,"port" => "3306"
    ,"name" => "cnpjrfb_2026"
    ,"user" => "root"
    ,"pass" => "123456" // ATENÇÃO: Verifique a senha
    ,"type" => "mysql"
    ,"prep" => "1"
    ,"slog" => "SystemSqlLogService"
];